
theme = "PaperMod"
baseURL = "/"
languageCode = "zh-tw"
title = "Rich-ard Blog"

# 添加選單配置
[menu]
  [[menu.main]]
    identifier = "javascript"
    name = "JavaScript"
    url = "/javascript/"   
    weight = 30
    
  [[menu.main]]
    identifier = "python"
    name = "Python"
    url = "/python/"      
    weight = 40

   [[menu.main]]
    identifier = "vue"
    name = "Vue"
    url = "/vue/"      
    weight = 50

    [[menu.main]]
    identifier = "other"
    name = "Other"
    url = "/other/"      
    weight = 60